/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arthur
 * Date: 07/03/2016
 * Programa que Adiciona e cria uma lista de Filmes/Livros/HQs para ler ou assistir
 * Update: 26/03/2017
 *  Dps documneto isso af
 * To Do: Botões e PopUp para ler
 */
import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
import javax.swing.JOptionPane;

import javax.swing.UIManager;// take this out


public class Culture extends javax.swing.JFrame {

    /**
     * Creates new form Culture
     */
    public Culture() {
        this.setTitle("Culture");
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch(Exception e){
            System.out.println("UIManager Exception : "+e);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HQ = new javax.swing.JButton();
        Filmes = new javax.swing.JButton();
        Livros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textField = new javax.swing.JTextField();
        readM = new javax.swing.JButton();
        readH = new javax.swing.JButton();
        readR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HQ.setText("HQs");
        HQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HQActionPerformed(evt);
            }
        });

        Filmes.setText("Movies");
        Filmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilmesActionPerformed(evt);
            }
        });

        Livros.setText("Books");
        Livros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivrosActionPerformed(evt);
            }
        });

        jLabel1.setText("Culture");

        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });

        readM.setText("Read");
        readM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readMActionPerformed(evt);
            }
        });

        readH.setText("Read");
        readH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readHActionPerformed(evt);
            }
        });

        readR.setText("Read");
        readR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Filmes, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(readM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Livros, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(readR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(HQ, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(readH))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(textField)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(240, 240, 240))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HQ)
                    .addComponent(Filmes)
                    .addComponent(Livros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readM)
                    .addComponent(readH)
                    .addComponent(readR)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HQActionPerformed
        // TODO add your handling code here:
        // TO DO : Fix Path
        FileNavigation movies = new FileNavigation("/Users/User/Desktop/Txt Archives & Stuff/List/HQ.txt");//,textField.getText()); // calls the class that do everything
        movies.fileWrite(textField.getText()); //The Function to write
        textField.setText("");// make it empty again
    }//GEN-LAST:event_HQActionPerformed

    private void FilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilmesActionPerformed
        FileNavigation movies = new FileNavigation("/Users/User/Desktop/Txt Archives & Stuff/List/To see.txt");
        movies.fileWrite(textField.getText());
        textField.setText("");
    }//GEN-LAST:event_FilmesActionPerformed

    private void LivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivrosActionPerformed
        // TODO add your handling code here:
        FileNavigation movies = new FileNavigation("/Users/User/Desktop/Txt Archives & Stuff/List/To read.txt");
        movies.fileWrite(textField.getText());
        textField.setText("");
    }//GEN-LAST:event_LivrosActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldActionPerformed

    private void readMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readMActionPerformed
        FileNavigation movies = new FileNavigation("/Users/User/Desktop/Txt Archives & Stuff/List/To see.txt");// TODO add your handling code here:
        String message = movies.fileRead();
        movies.fileShow(message);   //scrollPane, "An Error Has Occurred", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_readMActionPerformed

    private void readHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readHActionPerformed
        FileNavigation movies = new FileNavigation("/Users/User/Desktop/Txt Archives & Stuff/List/HQ.txt");// TODO add your handling code here:
        String message = movies.fileRead(); //"/Users/User/Desktop/teste/HQ.txt"
        movies.fileShow(message);
    }//GEN-LAST:event_readHActionPerformed

    private void readRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readRActionPerformed
        FileNavigation movies = new FileNavigation("/Users/User/Desktop/Txt Archives & Stuff/List/To read.txt");// TODO add your handling code here:
        String message = movies.fileRead();
        movies.fileShow(message);
    }//GEN-LAST:event_readRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Culture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Culture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Culture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Culture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Culture().setVisible(true);
            }
        });
    }      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Filmes;
    private javax.swing.JButton HQ;
    private javax.swing.JButton Livros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton readH;
    private javax.swing.JButton readM;
    private javax.swing.JButton readR;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
